### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Oddnoun** [muratdemirtas/MT7601u#2]
I am using the Tenda W311MI device and it is using the MT7061u driver. I am trying to use your driver but stuck on this step.

sudo cp -v /lib/modules/$(uname -r)/build/Module.symvers src/os/linux
My version is 4.9.41+ and I am getting an error that says No such file or directory.
I am using raspbian stretch and pi zero w.

Any advice on a workaround would be greatly appreciated and thank you for this solution.

**Comment by JoanTheSpark** [comment]
I think the creator of this kernel module is cross compiling this on a Ubuntu machine for the RPi.
The steps to do this can be found here (answer by Diederik de Haas):
https://raspberrypi.stackexchange.com/questions/36900/how-do-i-get-the-configuration-and-module-symvers-for-a-raspbian-kernel-to-compi
Seems quite involved and not for the faint of heart.

**Comment by cyclone125** [comment]
You need to get Raspberry Pi linux headers using rpi-source (As it is written on the bottom of the page)

```
sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source  
sudo chmod +x /usr/bin/rpi-source 
/usr/bin/rpi-source -q --tag-update
sudo rpi-source
```

If rpi-source throws a GCC error (something about a version mismatch), it's okay as long as your current GCC version is higher. Run `rpi-source --skip-gcc` instead of `rpi-source`

Wait until files are being unpacked.
This should fix this issue.
